var gTime = 30;
var easy = [
	["куче", "assets/images/dog.png"],
	["орел", "assets/images/eagle.png"],
	["слон", "assets/images/elephant.png"],
	["чаша", "assets/images/cup.png"],
	["елен", "assets/images/deer.png"],
	["сече", "assets/images/cut.png"],
	["Лав", "assets/images/lion.png"],
	["ној", "assets/images/ostrich.png"],
	["був", "assets/images/owl.png"],
	["јак", "assets/images/yak.png"],
	["вол", "assets/images/ox.png"],
	["тава", "assets/images/pan.png"],
	["дете", "assets/images/kid.png"],
	["киви", "assets/images/kiwi.png"],
	["Личи", "assets/images/lichu.png"],
	["џем", "assets/images/jam.png"],
	["капа", "assets/images/hat.png"],
	["џогер", "assets/images/mop.png"],
	["патка", "assets/images/duck.png"],
	["манго", "assets/images/mango.png"]
];

var normal =[
	["лимон", "assets/images/lemon.png"],
	["палка", "assets/images/bat.png"],
	["мечка", "assets/images/bear.png"],
	["кревет", "assets/images/bed.png"],
	["кутија", "assets/images/box.png"],
	["камила", "assets/images/camel.png"],
	["мачка", "assets/images/cat.png"],
	["круши", "assets/images/pears.png"],
	["свиња", "assets/images/pig.png"],
	["гулаб", "assets/images/pigeon.png"],
	["ананас", "assets/images/pineapple.png"],
	["тажен", "assets/images/sad.png"],
	["змија", "assets/images/snake.png"],
	["Тигар", "assets/images/tiger.png"],
	["домат", "assets/images/tomato.png"],
	["желка", "assets/images/tortoise.png"],
	["комбе", "assets/images/van.png"],
	["зебра", "assets/images/zebra.png"],
	["цреша", "assets/images/cherry.png"],
	["Гуава", "assets/images/guava.png"]
];

var hard = [
	["крокодил", "assets/images/crocodile.png"],
	["банана", "assets/images/banana.png"],
	["копаат", "assets/images/dig.png"],
	["лисица", "assets/images/fox.png"],
	["грозје", "assets/images/grape.png"],
	["кокошка", "assets/images/hen.png"],
	["кенгур", "assets/images/kangaroo.png"],
	["дневник", "assets/images/log.png"],
	["кригла", "assets/images/mug.png"],
	["портокалова", "assets/images/orange.png"],
	["лубеница", "assets/images/watermelon.png"],
	["автобус", "assets/images/bus.png"],
	["стаорец", "assets/images/rat.png"],
	["калинка", "assets/images/pomegranate.png"],
	["тенџере", "assets/images/pot.png"],
	["гепард", "assets/images/cheetah.png"],
	["полжав", "assets/images/snail.png"],
	["влажни", "assets/images/wet.png"],
	["јагода", "assets/images/strawberry.png"],
	["зајаци", "assets/images/rabbit.png"]
];
